test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id:     <%= ENV['AKIAUBZGPBRNX53YCE5I'] %>
  secret_access_key: <%= ENV['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'] %>
  region:            <%= ENV['region=ap-northeast-1'] %>
  bucket:            <%= ENV['readcomics'] %>